### PR TITLE
XIVY-11980 use native yaml types in toVariables

### PR DESCRIPTION
**Pull request by ivy-lgi**

### CODE REVIEW

**Review by ivy-lli — APPROVED** [review]
Cool 👍

**Comment by ivy-lli** [comment]
I think as you now have integrated the editor in vscode you can delete the old editor right?

**Comment by ivy-lgi** [comment]
> I think as you now have integrated the editor in vscode you can delete the old editor right?

Once I merged the other PR, yes :smile:

**Review by weissreto — COMMENTED** [review]
👍

**Pull request merged**
