### PR TITLE
Add raise-deps file to .ivy

### PR DESCRIPTION
**Pull request by ivy-edp**

### CODE REVIEW

**Review by ivy-lli — CHANGES_REQUESTED** [review]
I didn't want to approve :D

**Review by ivy-lli — APPROVED** [review]
Looks good 👍 
have you tried it?

**Comment by ivy-edp** [comment]
> Looks good 👍 have you tried it?

Looks good to me but had to add the update:axonivy:next command.
grafik

**Comment by ivy-lli** [comment]
> > Looks good 👍 have you tried it?
> 
> @ivy-lli Looks good to me but had to add the update:axonivy:next command. grafik

have you run it with SHAPSHOT?

but yes looks fine 👍

**Pull request merged**
